FROM node:20-alpine
WORKDIR /app
COPY frontend/.next/standalone ./
COPY frontend/.next/static ./.next/static
COPY frontend/public ./public
ENV NODE_ENV=production
ENV PORT=3002
EXPOSE 3002
CMD ["node", "server.js"]
